name: avenue

on:
  push:
    branches: 
      - master
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    - name: Use Node.js lts
      uses: actions/setup-node
      with:
        node-version: lts
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: true
    - run: npm run deploy
      if: startsWith(github.ref, 'tags/')
